In [1]:
a=10

In [2]:
b=100

In [3]:
c=a+b

In [4]:
print(c)

110


In [5]:
import pandas as pd

In [6]:
df=pd.read_excel(r"C:\Users\sudhanshu pandey\Downloads\apollo-contacts-export (3).xls")

In [7]:
df.shape

(700, 62)

In [8]:
df.columns

Index(['First Name', 'Last Name', 'Title', 'Company',
       'Company Name for Emails', 'Email', 'Email Status',
       'Primary Email Source', 'Email Confidence',
       'Primary Email Catch-all Status', 'Primary Email Last Verified At',
       'Seniority', 'Departments', 'Contact Owner', 'Work Direct Phone',
       'Home Phone', 'Mobile Phone', 'Corporate Phone', 'Other Phone', 'Stage',
       'Lists', 'Last Contacted', 'Account Owner', '# Employees', 'Industry',
       'Keywords', 'Person Linkedin Url', 'Website', 'Company Linkedin Url',
       'Facebook Url', 'Twitter Url', 'City', 'State', 'Country',
       'Company Address', 'Company City', 'Company State', 'Company Country',
       'Company Phone', 'Technologies', 'Annual Revenue', 'Total Funding',
       'Latest Funding', 'Latest Funding Amount', 'Last Raised At',
       'Subsidiary of', 'Email Sent', 'Email Open', 'Email Bounced', 'Replied',
       'Demoed', 'Number of Retail Locations', 'Apollo Contact Id',
       'Apollo Acc

In [10]:
df.head(5)

,First Name,Last Name,Title,Company,Company Name for Emails,Email,Email Status,Primary Email Source,Email Confidence,Primary Email Catch-all Status,...,Apollo Contact Id,Apollo Account Id,Secondary Email,Secondary Email Source,Tertiary Email,Tertiary Email Source,Primary Intent Topic,Primary Intent Score,Secondary Intent Topic,Secondary Intent Score
0,Craig,Robin,Chief Executive Officer,EO Solutions,EO Solutions,craig.robin@e-o.solutions,Verified,Apollo,NaN,Not Catch-all,...,689b44491c1e3000019117b0,689b444f1c1e300001911c33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Silvia,Justo,Socia Fundadora y Directora de Operaciones,ARKANA,ARKANA,silvia@emma.io,Verified,Apollo,NaN,Catch-all,...,689b444a1c1e300001911824,689b444f1c1e300001911bff,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Robert,Willis,Chief Technology Officer,WYSR,WYSR,rwillis@wysr.com,Verified,Apollo,NaN,Not Catch-all,...,689b444a1c1e30000191182d,689b444f1c1e300001911c97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Vincent,Fontana,Managing Director,Demandgine,Demandgine,vincent@demandgine.com,Verified,Apollo,NaN,Catch-all,...,689b444a1c1e30000191187a,689b444f1c1e300001911cc7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mike,Dunlap,General Manager,Sunstack Racking,Sunstack Racking,michael.dunlap@sunstackracking.com,Verified,Apollo,NaN,Catch-all,...,689b444a1c1e3000019118fb,689b444f1c1e300001911d04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [11]:
import numpy 

In [ ]:
###NUMPY is used to built array it means "numerical in python"
###Array is the collection of homogeneous(same datatype) elements.

In [12]:
arr=numpy.array([1,2,3,4,5,6,7])

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
import numpy as np

In [15]:
arr=np.array([1,2,3,5,678,567])

In [16]:
arr

array([  1,   2,   3,   5, 678, 567])

In [17]:
arr=np.array([1,2,3,4, 5.6])

In [18]:
arr

array([1. , 2. , 3. , 4. , 5.6])

In [19]:
arr=np.array([1,2,3,4,'A', 5])

In [20]:
arr

array(['1', '2', '3', '4', 'A', '5'], dtype='<U21')

In [ ]:
# array, arange, linspace   {arange= (array + range)giving range how much range is to be print,  linspace=linearspace}

In [27]:
arr=np.arange(1,21,1)

In [28]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
arr=np.linspace(0.5 , 5)

In [30]:
arr

array([0.5       , 0.59183673, 0.68367347, 0.7755102 , 0.86734694,
       0.95918367, 1.05102041, 1.14285714, 1.23469388, 1.32653061,
       1.41836735, 1.51020408, 1.60204082, 1.69387755, 1.78571429,
       1.87755102, 1.96938776, 2.06122449, 2.15306122, 2.24489796,
       2.33673469, 2.42857143, 2.52040816, 2.6122449 , 2.70408163,
       2.79591837, 2.8877551 , 2.97959184, 3.07142857, 3.16326531,
       3.25510204, 3.34693878, 3.43877551, 3.53061224, 3.62244898,
       3.71428571, 3.80612245, 3.89795918, 3.98979592, 4.08163265,
       4.17346939, 4.26530612, 4.35714286, 4.44897959, 4.54081633,
       4.63265306, 4.7244898 , 4.81632653, 4.90816327, 5.        ])

In [31]:
arr=np.linspace(0.5 , 5, 10)

In [32]:
arr

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
#List vs Array
# arrays work on addresses and play with the elements by their addresses not with values ..soppuse i need 4rth index number element so it just tarverse 
      # by the memory address
## EX:

#arr=np.array([112,234,456,678,68,89])
#arr-> startting address let 2024
# arr[4]= 2024 + 4*8bytes =2056 address ka elemnt is the answer


#but in list it just traverse with values