In [1]:
import numpy as np

In [ ]:
#list=> Heterogeneous, Nodes (Random References), Dynamic size, fast in insertion and deletion 
#Array=> Homogeneous, (Contigous references), Static size, fast in searching and sorting

In [ ]:
#Array is multidimensional

In [2]:
arr=np.array([34,35,36])

In [3]:
arr

array([34, 35, 36])

In [ ]:
#0th dimensional array

In [4]:
arr=np.array(37)
print(arr)
print(arr.shape)
print(arr.ndim)

37
()
0


In [ ]:
#1st dimensional array

In [6]:
arr=np.array([23, 45,34,35])
print(arr)
print(arr.shape)
print(arr.ndim)

[23 45 34 35]
(4,)
1


In [ ]:
#2nd dimensional array

In [7]:
arr=np.array([ [1,2,3,4], [5,6,7,8], [9,10,11,12] ])
print(arr)
print(arr.shape)
print(arr.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [ ]:
#3rd dimensional array

In [ ]:
arr=np.array

In [11]:
arr=np.array([ [ [1,2,3,4], [5,6,7,8], [9,10,11,12] ] ])
print(arr)
print(arr.shape)
print(arr.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
(1, 3, 4)
3


In [ ]:
#ones, zeroes, full, eye, identity

In [12]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
np.full((3,3),  2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [18]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.identity(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
# eye => make identity matrix but we can also pass row and colummn by our own choice ,,,whereas in identity matrix we only pass single square matrix 

In [22]:
np.eye(3,4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [23]:
np.nan

nan

In [24]:
np.number

numpy.number

In [25]:
arr=np.array([[1,2,3,4], [5,6,7,8], [0,6,7,8]])

In [26]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 6, 7, 8]])

In [27]:
arr*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [ 0, 12, 14, 16]])

In [28]:
arr+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [ 2,  8,  9, 10]])

In [29]:
arr/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [0. , 3. , 3.5, 4. ]])